# Generated by Django 2.0.5 on 2018-08-19 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=250)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emailAddress', models.EmailField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('billingAddress', models.CharField(max_length=250)),
                ('billingCity', models.CharField(max_length=250)),
                ('billingPostcode', models.CharField(max_length=250)),
                ('billingCountry', models.CharField(max_length=250)),
                ('shippingName', models.CharField(max_length=250)),
                ('shippingAddress', models.CharField(max_length=250)),
                ('shippingCity', models.CharField(max_length=250)),
                ('shippingPostcode', models.CharField(max_length=250)),
                ('shippingCountry', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'Order',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=250)),
                ('quantity', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=250)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
            options={
                'db_table': 'OrderItem',
            },
        ),
    ]
