# Generated by Django 2.0.5 on 2018-08-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billingName',
            field=models.CharField(default='billingName', max_length=250),
            preserve_default=False,
        ),
    ]
